site_name: simpleorm

site_url: https://simpleorm.readthedocs.io/en/latest

theme:
  name: material
  palette:
    scheme: default
    primary: indigo
    accent: indigo

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: USAGE.md

  - Roadmap: ROADMAP.md
  - Contribute: CONTRIBUTING.md
  - TODO: TODO.md

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - admonition
  - codehilite
  - footnotes
  - def_list
  - pymdownx.superfences
